In [46]:
import warnings

warnings.simplefilter(action="ignore", category=FutureWarning)

In [47]:
import pandas as pd

In [48]:
# Section 1 — Load Data
from src.data_loader import load_all_csvs
from src.config import RAW_DATA_PATH

dfs = load_all_csvs(RAW_DATA_PATH)

In [49]:
dfs["2015"]

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176
...,...,...,...,...,...,...,...,...,...,...,...,...
153,Rwanda,Sub-Saharan Africa,154,3.465,0.03464,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042
154,Benin,Sub-Saharan Africa,155,3.340,0.03656,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,1.63328
155,Syria,Middle East and Northern Africa,156,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858
156,Burundi,Sub-Saharan Africa,157,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302
157,Togo,Sub-Saharan Africa,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726

In [50]:
# Section 2 — Clean Data

#define dictionary for column name normalization. Based on predefined data of 2015-2019.

from src.config import COLUMN_MAPPING, COLUMNS_TO_KEEP, COL_FILE_ID, COL_SOURCE_ROW

# clean the names of all data frame columns so it can be worked with
# standardize the data frame according to column mapping and filter out unusuable ones.
# add file ID column to each so source can be identified after unification to one data frame.

from src.data_cleaner import standardize_df

for data_set_name in dfs:
  dfs[data_set_name] = standardize_df(dfs[data_set_name], data_set_name, COLUMN_MAPPING, COLUMNS_TO_KEEP, COL_SOURCE_ROW, COL_FILE_ID)

In [51]:
dfs['2018']

,source_row_index,country,rank,happiness_score,gdp_per_capita,social_support,life_expectancy,freedom,generosity,corruption,dystopia_residual,file_id
0,0,Finland,1,7.632,1.305,1.592,0.874,0.681,0.202,0.393,None,2018
1,1,Norway,2,7.594,1.456,1.582,0.861,0.686,0.286,0.340,None,2018
2,2,Denmark,3,7.555,1.351,1.590,0.868,0.683,0.284,0.408,None,2018
3,3,Iceland,4,7.495,1.343,1.644,0.914,0.677,0.353,0.138,None,2018
4,4,Switzerland,5,7.487,1.420,1.549,0.927,0.660,0.256,0.357,None,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
151,151,Yemen,152,3.355,0.442,1.073,0.343,0.244,0.083,0.064,None,2018
152,152,Tanzania,153,3.303,0.455,0.991,0.381,0.481,0.270,0.097,None,2018
153,153,South Sudan,154,3.254,0.337,0.608,0.177,0.112,0.224,0.106,None,2018
154,154,Central African Republic,155,3.083,0.024,0.000,0.010,0.305,0.218,0.038,None,2018
155,155,Burundi,156,2.905,0.091,0.627,0.145,0.065,0.149,0.076,None,2018

In [52]:
# unify all data frames to one data frame containing all data

combined_df = pd.concat(dfs, ignore_index=True)
combined_df

,source_row_index,country,rank,happiness_score,gdp_per_capita,social_support,life_expectancy,freedom,generosity,corruption,dystopia_residual,file_id
0,0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.29678,0.41978,2.51738,2015
1,1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.43630,0.14145,2.70201,2015
2,2,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.34139,0.48357,2.49204,2015
3,3,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.34699,0.36503,2.46531,2015
4,4,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.45811,0.32957,2.45176,2015
...,...,...,...,...,...,...,...,...,...,...,...,...
777,151,Rwanda,152,3.334,0.35900,0.71100,0.61400,0.55500,0.21700,0.41100,NaN,2019
778,152,Tanzania,153,3.231,0.47600,0.88500,0.49900,0.41700,0.27600,0.14700,NaN,2019
779,153,Afghanistan,154,3.203,0.35000,0.51700,0.36100,0.00000,0.15800,0.02500,NaN,2019
780,154,Central African Republic,155,3.083,0.02600,0.00000,0.10500,0.22500,0.23500,0.03500,NaN,2019
781,155,South Sudan,156,2.853,0.30600,0.57500,0.29500,0.01000,0.20200,0.09100,NaN,2019

In [53]:
# Data exploration and additional cleaning

from src.config import COL_DYSTOPIA

# print(combined_df[combined_df['country'] == 'Israel'])

# corruption missing one entry - dystopia missing years 2018 and 2019 - removing the column
combined_df.drop(columns=[COL_DYSTOPIA], inplace=True)

# minimal entry has some zeros across almost every field. seems like empty data to check and filter out.
combined_df.describe()

combined_df
# combined_df[combined_df["gdp_per_capita"] == 0]

# combined_df["country"].nunique()
# combined_df.loc[combined_df["file_id"] == '2015', "country"].nunique()
# combined_df.loc[combined_df["file_id"] == '2016', "country"].nunique()
# combined_df.loc[combined_df["file_id"] == '2017', "country"].nunique()
# combined_df.loc[combined_df["file_id"] == '2018', "country"].nunique()
# combined_df.loc[combined_df["file_id"] == '2019', "country"].nunique()

# seems like the numbers aren't exact - fetching the countries that show in all files:
# expected_years = combined_df["file_id"].nunique()

# missing_countries = (
#     combined_df.groupby("country")["file_id"].nunique()
#     .loc[lambda x: x < expected_years]
# )

# missing_countries

# seems : "Trinidad & Tobago", "Hong Kong", "Taiwan", all should be OK if name will be fixed
# combined_df[combined_df["country"].str.startswith("Taiwan", na=False)]
# searched for others - but all missing some years, so omitted.
# combined_df[combined_df['country'].str.contains("Gam", na=False)]

,source_row_index,country,rank,happiness_score,gdp_per_capita,social_support,life_expectancy,freedom,generosity,corruption,file_id
0,0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.29678,0.41978,2015
1,1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.43630,0.14145,2015
2,2,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.34139,0.48357,2015
3,3,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.34699,0.36503,2015
4,4,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.45811,0.32957,2015
...,...,...,...,...,...,...,...,...,...,...,...
777,151,Rwanda,152,3.334,0.35900,0.71100,0.61400,0.55500,0.21700,0.41100,2019
778,152,Tanzania,153,3.231,0.47600,0.88500,0.49900,0.41700,0.27600,0.14700,2019
779,153,Afghanistan,154,3.203,0.35000,0.51700,0.36100,0.00000,0.15800,0.02500,2019
780,154,Central African Republic,155,3.083,0.02600,0.00000,0.10500,0.22500,0.23500,0.03500,2019
781,155,South Sudan,156,2.853,0.30600,0.57500,0.29500,0.01000,0.20200,0.09100,2019

In [54]:
# Additional cleaning after exploration of data

# remove lines with 0 in any of the following columns.

from src.config import ANALYSIS_COLUMNS, COUNTRY_NAME_FIX, OUTPUT_FILE_FULL_PATH, COL_SOURCE_ROW, COL_COUNTRY, COL_FILE_ID
from src.data_writer import write_df_to_csv

# Remove rows with 0 in value for any of the analysis columns
combined_df = combined_df[~(combined_df[ANALYSIS_COLUMNS] == 0).any(axis=1)]

# fix names of countries (same country different name across different files
for key in COUNTRY_NAME_FIX:
  combined_df.loc[combined_df[COL_COUNTRY].str.startswith(key, na=False),
    COL_COUNTRY
] = COUNTRY_NAME_FIX[key]

#removing countries that don't have all years entries
expected_years = combined_df[COL_FILE_ID].nunique()

missing_countries = (
    combined_df.groupby(COL_COUNTRY)[COL_FILE_ID].nunique()
    .loc[lambda x: x < expected_years]
)

combined_df = combined_df[~combined_df[COL_COUNTRY].isin(missing_countries.index)]

# remove source row id - for debug purposes only
combined_df = combined_df.drop(columns=[COL_SOURCE_ROW])

combined_df

,country,rank,happiness_score,gdp_per_capita,social_support,life_expectancy,freedom,generosity,corruption,file_id
0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.29678,0.41978,2015
1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.43630,0.14145,2015
2,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.34139,0.48357,2015
3,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.34699,0.36503,2015
4,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.45811,0.32957,2015
...,...,...,...,...,...,...,...,...,...,...
774,Syria,149,3.462,0.61900,0.37800,0.44000,0.01300,0.33100,0.14100,2019
775,Malawi,150,3.410,0.19100,0.56000,0.49500,0.44300,0.21800,0.08900,2019
776,Yemen,151,3.380,0.28700,1.16300,0.46300,0.14300,0.10800,0.07700,2019
777,Rwanda,152,3.334,0.35900,0.71100,0.61400,0.55500,0.21700,0.41100,2019
778,Tanzania,153,3.231,0.47600,0.88500,0.49900,0.41700,0.27600,0.14700,2019

In [55]:
write_df_to_csv(combined_df, OUTPUT_FILE_FULL_PATH)

In [56]:
# Streamlit dashboard - generic for data (e.g. each column)

# !pip install streamlit

In [57]:
# Visulaiastion

# import streamlit as st
# import matplotlib.pyplot as plt
#
# st.title("🌍 World Happiness Dashboard")
#
# years = sorted(combined_df["file_id"].unique())
# selected_year = st.sidebar.selectbox("Select Year", years)
#
# countries = sorted(combined_df["country"].unique())
# selected_countries = st.sidebar.multiselect(
#     "Select Countries (for trends)",
#     countries,
#     default=["Israel", "United States"]
# )
#
#
# # -------------------------
# # Filtered data
# # -------------------------
# df_year = combined_df[combined_df["file_id"] == selected_year]
#
# # -------------------------
# # 1. Top Countries Bar Chart
# # -------------------------
# st.subheader(f"🏆 Top Countries in {selected_year}")
#
# top_n = st.slider("Top N countries", 5, 20, 10)
#
# top_df = df_year.sort_values(
#     by="happiness_score",
#     ascending=False
# ).head(top_n)
#
# fig, ax = plt.subplots()
# ax.barh(top_df["country"], top_df["happiness_score"])
# ax.invert_yaxis()
#
# st.pyplot(fig)